[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# No need for Go version since this is a Next.js project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 