[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

# Force trailing slashes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle route redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
